/*
 * This source file was generated by the Gradle 'init' task
 */
package run.resonance;

import java.util.HashMap;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import run.resonance.customization.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public HashMap<String, Customization> getCustomizations() {
        Gson gson = new Gson();
        TypeToken<HashMap<String, Customization>> mapType = new TypeToken<HashMap<String, Customization>>() {
        };
        String jsonResponse = "{\"MODAL\": {\"id\": \"ccc\", \"customizationTypeId\": \"feed-demo\"}}";
        HashMap<String, Customization> customization = gson.fromJson(jsonResponse, mapType);
        return customization;
    }
}
