/*
 * This source file was generated by the Gradle 'init' task
 */
package run.resonance;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;

import run.resonance.customization.Customization;

public class LibraryTest {
    @Test
    public void getCustomizationsReturnsCustomization() {
        Library classUnderTest = new Library();
        HashMap<String, Customization> result = classUnderTest.getCustomizations();
        Customization modalCustomization = result.get("MODAL");
        assertEquals("ccc", modalCustomization.id);
        assertEquals("feed-demo", modalCustomization.customizationTypeId);
    }
}
