/*
 * This source file was generated by the Gradle 'init' task
 */
package run.resonance;

import org.junit.Test;

import okhttp3.HttpUrl;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.HashMap;

import run.resonance.customization.Customization;
import run.resonance.mocks.TestUserData;

public class ResonanceClientTest {
    @Test
    public void getCustomizationsReturnsCustomization() {
        MockWebServer server = new MockWebServer();
        MockResponse response = new MockResponse()
                .addHeader("Content-Type", "application/json")
                .setBody(
                        "{\"customizations\": { \"MODAL\" : { \"id\": \"customization-id-123\", \"customizationTypeId\": \"feed-promo\", \"variation\": { \"id\": \"abc\", \"rampPercent\": 50, \"fields\": { \"nest\": { \"fields\": { \"greeting\": {\"value\": \"hi\" } } }, \"hello\": { \"value\": \"friends\" } } } } } }");

        server.enqueue(response);
        try {
            server.start();
            HttpUrl baseUrl = server.url("/");

            ResonanceClient<TestUserData> classUnderTest = new ResonanceClient<TestUserData>(baseUrl.toString(),
                    "a.fake.api.key", "a-fake-client-id");
            HashMap<String, Object> defaultValue = new HashMap<String, Object>();
            defaultValue.put("hello", "world");
            HashMap<String, Object> modalCustomization = classUnderTest.getCustomizations(new TestUserData("123"),
                    "feed-promo",
                    "MODAL", defaultValue);

            assertEquals("friends", modalCustomization.get("hello"));
            HashMap<String, String> expectedNestValue = new HashMap<String, String>();
            expectedNestValue.put("greeting", "hi");
            assertEquals(expectedNestValue, modalCustomization.get("nest"));

            server.shutdown();
        } catch (IOException exception) {
            assertEquals(false, true);
        }

    }

    @Test
    public void getCustomizationsReturnsDefaultIfNoCustomizationFound() {
        MockWebServer server = new MockWebServer();
        MockResponse response = new MockResponse()
                .addHeader("Content-Type", "application/json")
                .setBody(
                        "{\"customizations\": {} }");

        server.enqueue(response);
        try {
            server.start();
            HttpUrl baseUrl = server.url("/");

            ResonanceClient<TestUserData> classUnderTest = new ResonanceClient<TestUserData>(baseUrl.toString(),
                    "a.fake.api.key", "a-fake-client-id");
            HashMap<String, Object> defaultValue = new HashMap<String, Object>();
            defaultValue.put("hello", "world");
            HashMap<String, Object> modalCustomization = classUnderTest.getCustomizations(new TestUserData("123"),
                    "feed-promo",
                    "MODAL", defaultValue);

            assertEquals("world", modalCustomization.get("hello"));

            server.shutdown();
        } catch (IOException exception) {
            assertEquals(false, true);
        }

    }
}
